[theme]
base = "dark"
backgroundColor = "#080808"
secondaryBackgroundColor = "#121212"
primaryColor = "#FFB800"
textColor = "#F5F5F5"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true